name: example
description: Demonstrates how to use the sc_statistics plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sc_statistics:
    path: ../
  flutter_curiosity: ^5.0.2

dev_dependencies:
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
