name: sc_statistics
description: Sichuan Province platform information integration module for flutter
version: 1.2.0
repository: https://github.com/Wayaer/sc_statistics.git

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: sc.statistics
        pluginClass: SCStatisticsPlugin
      ios:
        pluginClass: SCStatisticsPlugin
