name: sc_statistics
description: Sichuan Province platform information integration module for flutter
version: 1.1.1
repository: https://github.com/Wayaer/sc_statistics.git

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: sc.statistics
        pluginClass: SCStatisticsPlugin
      ios:
        pluginClass: SCStatisticsPlugin
