name: sc_statistics
description: Sichuan Province platform information integration module for flutter
version: 0.0.1
repository: https://github.com/Wayaer/sc_statistics.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: fl.sc.statistics
        pluginClass: SCStatisticsPlugin
      ios:
        pluginClass: SCStatisticsPlugin
